version: '3'
services:
  mq-scheduler-in:
    image: biocad/mq-scheduler-in
    restart: always
    ports:
      - "9000:9000"
      - "9024:9024"
    volumes:
      - ${PWD}/config-compose.json:/workdir/config.json:ro

  mq-scheduler-out:
    image: biocad/mq-scheduler-out
    restart: always
    ports:
      - "9001:9001"
      - "9025:9025"
    volumes:
      - ${PWD}/config-compose.json:/workdir/config.json:ro

  mq-scheduler-logic:
    image: biocad/mq-scheduler-logic
    restart: always
    links:
      - mq-scheduler-in
      - mq-scheduler-out
    volumes:
      - ${PWD}/config-compose.json:/workdir/config.json:ro

  mq-controller:
    image: biocad/mq-controller
    restart: always
    links:
      - mq-scheduler-in
      - mq-scheduler-out
    ports:
      - "10000-10500:10000-10500"
    volumes:
      - ${PWD}/config-controller-compose.json:/workdir/config.json:ro
